makefile is literally perfect

diff --git a/sh/check b/sh/check
--- a/sh/check
+++ b/sh/check
@@ -2,23 +2,26 @@
 
 CHECKSTATUS=0
 QUIETEXIT=0
+INSTALL_ATTEMPT=0
 
-if which datab >/dev/null; then
+if ! which datab >/dev/null; then
    CHECKSTATUS=$(($CHECKSTATUS | 1))
 fi
-if ldconfig -p | grep -q '\<libssh2.so\.[0-9]\+>'; then
+if ! [ -f /usr/include/libssh2.h ] && ! [ -f /usr/lib/libssh2.so ]; then
    CHECKSTATUS=$(($CHECKSTATUS | 2))
 fi
-if [ -f /usr/include/argon2.h ] && [ -f /usr/lib/libargon2.so ]; then
+if ! [ -f /usr/include/argon2.h ] && ! [ -f /usr/lib/libargon2.so ]; then
    CHECKSTATUS=$(($CHECKSTATUS | 4))
 fi
 
 usage()
 {
-   echo "usage: $0 [-h | -t | -s | -q]"
+   echo "usage: $0 [-h | -t | -s | -i=INSTALL_ATTEMPT | -q]"
    echo "   -h print this message"
    echo "   -t print necessary make targets"
    echo "   -s print dependency status"
+   echo "   -i prints installation success/failure message"
+   echo "      where INSTALL_ATTEMPT is an octal number"
    echo "   -q always exit with 0"
    echo ""
    echo "exit status is an octal status value"
@@ -27,28 +30,49 @@ usage()
 print_status()
 {
    if (($CHECKSTATUS & 1)); then
-      echo -e "       datab      \e[32mPRESENT\e[0m"
+      echo -e "     datab   \e[31mMISSING\e[0m"
    else
-      echo -e "       datab      \e[31mMISSING\e[0m"
+      echo -e "     datab   \e[32mPRESENT\e[0m"
    fi
    if (($CHECKSTATUS & 2)); then
-      echo -e "     libssh2.so   \e[32mPRESENT\e[0m"
+      echo -e "   libssh2   \e[31mMISSING\e[0m"
    else
-      echo -e "     libssh2.so   \e[31mMISSING\e[0m"
+      echo -e "   libssh2   \e[32mPRESENT\e[0m"
    fi
    if (($CHECKSTATUS & 4)); then
-      echo -e "      argon2      \e[32mPRESENT\e[0m"
+      echo -e "    argon2   \e[31mMISSING\e[0m"
    else
-      echo -e "      argon2      \e[31mMISSING\e[0m"
+      echo -e "    argon2   \e[32mPRESENT\e[0m"
+   fi
+}
+
+print_install_status()
+{
+   if ! (($INSTALL_ATTEMPT & $CHECKSTATUS)); then
+      return;
+   fi
+
+   echo -e "\e[2;7;31mFAILED TO INSTALL THE FOLLOWING:\e[0m"
+
+   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 1)); then
+      echo -e "   \e[31m- datab\e[0m"
+   fi
+
+   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 2)); then
+      echo -e "   \e[31m- libssh2\e[0m"
+   fi
+
+   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 4)); then
+      echo -e "   \e[31m- argon2\e[0m"
    fi
 }
 
 print_targets()
 {
-   if ! (($CHECKSTATUS & 2)); then
+   if (($CHECKSTATUS & 2)); then
       echo -n "install-libssh2 "
    fi
-   if ! (($CHECKSTATUS & 4)); then
+   if (($CHECKSTATUS & 4)); then
       echo -n "install-argon2 "
    fi
    if [ "$CHECKSTATUS" -gt 0 ]; then
@@ -56,7 +80,7 @@ print_targets()
    fi
 }
 
-while getopts "htsq" flag; do
+while getopts "htsi:q" flag; do
    case $flag in
       h)
          usage
@@ -67,6 +91,10 @@ while getopts "htsq" flag; do
       s)
          print_status
          ;;
+      i)
+         INSTALL_ATTEMPT=$OPTARG
+         print_install_status
+         ;;
       q)
          QUIETEXIT=1
          ;;
@@ -76,8 +104,8 @@ while getopts "htsq" flag; do
    esac
 done
 
-if ! [ QUIETEXIT ]; then
-   exit $CHECKSTATUS
-else
-   exit 0
+if  [ QUIETEXIT ]; then
+   exit 0;
 fi
+
+exit $CHECKSTATUS
